# vim: expandtab tabstop=2 shiftwidth=2
name: Build Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build for ${{ matrix.ghidra-version }}
    strategy:
      fail-fast: false
      matrix:
        ghidra-version:
          - "latest"
          - "10.2.3"

    runs-on: ubuntu-latest
    container: "ghcr.io/${{ github.repository_owner }}/ghidra-container:${{ matrix.ghidra-version }}"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Compile for ${{ matrix.ghidra-version }}
        working-directory: FindCrypt
        run: |
          gradle
          ls -lah dist/

      - name: Upload FindCrypt for ${{ matrix.ghidra-version }}
        uses: actions/upload-artifact@v2
        with:
          name: ghidra_${{ matrix.ghidra-version }}_FindCrypt
          path: |
            README.md
            FindCrypt/dist/*.zip
          if-no-files-found: error
